/*
 *  File: Products.js
 *  Generated by: Mongoose-Fixture (v0.3.0)
 *
 */

// @callback must be returned
// expects (err, object)
// object can be an array of data-documents, or a kwarg['dataFixtures']

module.exports = function(mongoose, conn, callback){

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];
    
    /*
     * Example of adding a data document/fixture item 
     */
    fixture.push({
        // by not defining an _id mongoose-fixture
        // will by default set a mongo ObjectID
        // defining one manually will override mongoDB
        name:'Toy Box',
        price:9.99,
        qty:20,
        tags:['toys','children','storage']
    });
    
    // an additional example
    fixture.push({
        name:'Baseball Bat',
        price:29.99,
        qty:6,
        tags:['sporting','baseball','outdoors']
    });
    
    
    // mongoose-fixture expects implementor to return
    // the callback passed in context
    return callback(error, fixture);
};
