/*
 *  File: ProductSchema.js
 *  Generated by: Mongoose-Fixture (v0.2.0)
 *
 *  
 */

module.exports = function(mongoose){
        
    var exportSchema = mongoose.Schema({
        _id:{type:String},
        name:{type:String},
        price:{type:Number},
        qty:{type:Number},
        tags:{type:Array}
    });

    return exportSchema;
};
